blank_issues_enabled: false
contact_links:
  - name: Mention us on X (formerly known as Twitter)
    url: https://twitter.com/palera1n
    about: Mention us about your issue if you're not comfortable with using Github issues.
